version: '3.7'
services:
  drf_postgres:
    image: postgres:12.0-alpine
    env_file:
      - '${pg_env_file}'
    ports:
      - "5432:5432"
    volumes:
      - drf_postgres:/var/lib/db
    networks:
      drf-example-net:
        aliases:
          - drf_postgres
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '${env_file}'
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/backend
    networks:
      drf-example-net:
    depends_on:
      - drf_postgres

volumes:
  drf_postgres:

networks:
  drf-example-net:
