# Generated by Django 4.0.5 on 2022-06-26 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price.', max_digits=20)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
